/*
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MclrDslProposalProvider extends AbstractMclrDslProposalProvider {
}
