/*
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MclrDslStandaloneSetup extends MclrDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MclrDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
