/*
 * generated by Xtext 2.11.0.RC2
 */
package test.multiname.dsl.validation

import test.multiname.dsl.multiNameDsl.Funcs
import org.eclipse.xtext.validation.Check
import test.multiname.dsl.multiNameDsl.VarName
import test.multiname.dsl.multiNameDsl.MultiNameDslPackage
import test.multiname.dsl.multiNameDsl.FuncName

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MultiNameDslValidator extends AbstractMultiNameDslValidator {

//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MultiNameDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	@Check
	def checkFuncContext(Funcs func) {
		if (func.bracket) {
			if (!(func.right instanceof VarName)) {
				warning("Right hand size must be of Var type", 
					MultiNameDslPackage.Literals.FUNCS__RIGHT
				)
			}
		} else {
			if (!(func.right instanceof FuncName)) {
				warning("Right hand size must be of Function type", 
					MultiNameDslPackage.Literals.FUNCS__RIGHT
				)
			}
		}
	}
}
