/**
 * generated by Xtext 2.11.0.RC2
 */
package test.multiname.dsl.multiNameDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Func Name</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see test.multiname.dsl.multiNameDsl.MultiNameDslPackage#getFuncName()
 * @model
 * @generated
 */
public interface FuncName extends Name
{
} // FuncName
