/**
 * generated by Xtext 2.11.0.RC2
 */
package test.multiname.dsl.multiNameDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link test.multiname.dsl.multiNameDsl.Model#getModules <em>Modules</em>}</li>
 * </ul>
 *
 * @see test.multiname.dsl.multiNameDsl.MultiNameDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Modules</b></em>' containment reference list.
   * The list contents are of type {@link test.multiname.dsl.multiNameDsl.Module}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modules</em>' containment reference list.
   * @see test.multiname.dsl.multiNameDsl.MultiNameDslPackage#getModel_Modules()
   * @model containment="true"
   * @generated
   */
  EList<Module> getModules();

} // Model
