/**
 * generated by Xtext 2.11.0.RC2
 */
package test.multiname.dsl.multiNameDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vars</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see test.multiname.dsl.multiNameDsl.MultiNameDslPackage#getVars()
 * @model
 * @generated
 */
public interface Vars extends EObject
{
} // Vars
