/*
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMclrDslScopeProvider extends DelegatingScopeProvider {
}
