/*
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MclrDslUiModule extends AbstractMclrDslUiModule {
}
