/*
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MclrDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("tuks/mcrl2/dsl/parser/antlr/internal/InternalMclrDsl.tokens");
	}
}
