/*
 * generated by Xtext 2.11.0.RC2
 */
package test.multiname.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMultiNameDslScopeProvider extends DelegatingScopeProvider {
}
