grammar test.multiname.dsl.MultiNameDsl with org.eclipse.xtext.common.Terminals

generate multiNameDsl "http://www.multiname.test/dsl/MultiNameDsl"

Model:
	modules+=Module+;

Module:
	'begin_module' name=ID
	vars+=Vars*
	funcs+=Funcs*
	'end_module';

VarName:
	name=ID;

FuncName:
	name=ID;

Name:
	VarName | FuncName;

Funcs:
	'func' left=FuncName (bracket?='(' ')')? '=' right=[Name] ';';

Vars:
	'var' varName=VarName ';';
	

