/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import tuks.mcrl2.dsl.mclrDsl.BagEnumElt;
import tuks.mcrl2.dsl.mclrDsl.BagEnumEltList;
import tuks.mcrl2.dsl.mclrDsl.MclrDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bag Enum Elt List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.BagEnumEltListImpl#getBag_list <em>Bag list</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BagEnumEltListImpl extends MinimalEObjectImpl.Container implements BagEnumEltList
{
  /**
   * The cached value of the '{@link #getBag_list() <em>Bag list</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBag_list()
   * @generated
   * @ordered
   */
  protected EList<BagEnumElt> bag_list;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BagEnumEltListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclrDslPackage.Literals.BAG_ENUM_ELT_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<BagEnumElt> getBag_list()
  {
    if (bag_list == null)
    {
      bag_list = new EObjectContainmentEList<BagEnumElt>(BagEnumElt.class, this, MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST);
    }
    return bag_list;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST:
        return ((InternalEList<?>)getBag_list()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST:
        return getBag_list();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST:
        getBag_list().clear();
        getBag_list().addAll((Collection<? extends BagEnumElt>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST:
        getBag_list().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.BAG_ENUM_ELT_LIST__BAG_LIST:
        return bag_list != null && !bag_list.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BagEnumEltListImpl
