/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tuks.mcrl2.dsl.mclrDsl.ConstrDecl;
import tuks.mcrl2.dsl.mclrDsl.ConstrName;
import tuks.mcrl2.dsl.mclrDsl.MclrDslPackage;
import tuks.mcrl2.dsl.mclrDsl.ProjDeclList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constr Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.ConstrDeclImpl#getId <em>Id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.ConstrDeclImpl#getProj <em>Proj</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.ConstrDeclImpl#getRight_id <em>Right id</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstrDeclImpl extends MinimalEObjectImpl.Container implements ConstrDecl
{
  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected ConstrName id;

  /**
   * The cached value of the '{@link #getProj() <em>Proj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProj()
   * @generated
   * @ordered
   */
  protected ProjDeclList proj;

  /**
   * The default value of the '{@link #getRight_id() <em>Right id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight_id()
   * @generated
   * @ordered
   */
  protected static final String RIGHT_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRight_id() <em>Right id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight_id()
   * @generated
   * @ordered
   */
  protected String right_id = RIGHT_ID_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstrDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclrDslPackage.Literals.CONSTR_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstrName getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetId(ConstrName newId, NotificationChain msgs)
  {
    ConstrName oldId = id;
    id = newId;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.CONSTR_DECL__ID, oldId, newId);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setId(ConstrName newId)
  {
    if (newId != id)
    {
      NotificationChain msgs = null;
      if (id != null)
        msgs = ((InternalEObject)id).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.CONSTR_DECL__ID, null, msgs);
      if (newId != null)
        msgs = ((InternalEObject)newId).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.CONSTR_DECL__ID, null, msgs);
      msgs = basicSetId(newId, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.CONSTR_DECL__ID, newId, newId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProjDeclList getProj()
  {
    return proj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProj(ProjDeclList newProj, NotificationChain msgs)
  {
    ProjDeclList oldProj = proj;
    proj = newProj;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.CONSTR_DECL__PROJ, oldProj, newProj);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProj(ProjDeclList newProj)
  {
    if (newProj != proj)
    {
      NotificationChain msgs = null;
      if (proj != null)
        msgs = ((InternalEObject)proj).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.CONSTR_DECL__PROJ, null, msgs);
      if (newProj != null)
        msgs = ((InternalEObject)newProj).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.CONSTR_DECL__PROJ, null, msgs);
      msgs = basicSetProj(newProj, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.CONSTR_DECL__PROJ, newProj, newProj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRight_id()
  {
    return right_id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRight_id(String newRight_id)
  {
    String oldRight_id = right_id;
    right_id = newRight_id;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.CONSTR_DECL__RIGHT_ID, oldRight_id, right_id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MclrDslPackage.CONSTR_DECL__ID:
        return basicSetId(null, msgs);
      case MclrDslPackage.CONSTR_DECL__PROJ:
        return basicSetProj(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MclrDslPackage.CONSTR_DECL__ID:
        return getId();
      case MclrDslPackage.CONSTR_DECL__PROJ:
        return getProj();
      case MclrDslPackage.CONSTR_DECL__RIGHT_ID:
        return getRight_id();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MclrDslPackage.CONSTR_DECL__ID:
        setId((ConstrName)newValue);
        return;
      case MclrDslPackage.CONSTR_DECL__PROJ:
        setProj((ProjDeclList)newValue);
        return;
      case MclrDslPackage.CONSTR_DECL__RIGHT_ID:
        setRight_id((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.CONSTR_DECL__ID:
        setId((ConstrName)null);
        return;
      case MclrDslPackage.CONSTR_DECL__PROJ:
        setProj((ProjDeclList)null);
        return;
      case MclrDslPackage.CONSTR_DECL__RIGHT_ID:
        setRight_id(RIGHT_ID_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.CONSTR_DECL__ID:
        return id != null;
      case MclrDslPackage.CONSTR_DECL__PROJ:
        return proj != null;
      case MclrDslPackage.CONSTR_DECL__RIGHT_ID:
        return RIGHT_ID_EDEFAULT == null ? right_id != null : !RIGHT_ID_EDEFAULT.equals(right_id);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (right_id: ");
    result.append(right_id);
    result.append(')');
    return result.toString();
  }

} //ConstrDeclImpl
