/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import tuks.mcrl2.dsl.mclrDsl.DataExpr;
import tuks.mcrl2.dsl.mclrDsl.DataExpr1;
import tuks.mcrl2.dsl.mclrDsl.DataExprList;
import tuks.mcrl2.dsl.mclrDsl.MclrDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Expr</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.DataExprImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.DataExprImpl#getRight_1 <em>Right 1</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.DataExprImpl#getRight_2 <em>Right 2</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.impl.DataExprImpl#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DataExprImpl extends MinimalEObjectImpl.Container implements DataExpr
{
  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected DataExpr1 left;

  /**
   * The cached value of the '{@link #getRight_1() <em>Right 1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight_1()
   * @generated
   * @ordered
   */
  protected DataExpr right_1;

  /**
   * The cached value of the '{@link #getRight_2() <em>Right 2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight_2()
   * @generated
   * @ordered
   */
  protected DataExpr right_2;

  /**
   * The cached value of the '{@link #getRight() <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRight()
   * @generated
   * @ordered
   */
  protected DataExprList right;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MclrDslPackage.Literals.DATA_EXPR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataExpr1 getLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeft(DataExpr1 newLeft, NotificationChain msgs)
  {
    DataExpr1 oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__LEFT, oldLeft, newLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLeft(DataExpr1 newLeft)
  {
    if (newLeft != left)
    {
      NotificationChain msgs = null;
      if (left != null)
        msgs = ((InternalEObject)left).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__LEFT, null, msgs);
      if (newLeft != null)
        msgs = ((InternalEObject)newLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__LEFT, null, msgs);
      msgs = basicSetLeft(newLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__LEFT, newLeft, newLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataExpr getRight_1()
  {
    return right_1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRight_1(DataExpr newRight_1, NotificationChain msgs)
  {
    DataExpr oldRight_1 = right_1;
    right_1 = newRight_1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT_1, oldRight_1, newRight_1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRight_1(DataExpr newRight_1)
  {
    if (newRight_1 != right_1)
    {
      NotificationChain msgs = null;
      if (right_1 != null)
        msgs = ((InternalEObject)right_1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT_1, null, msgs);
      if (newRight_1 != null)
        msgs = ((InternalEObject)newRight_1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT_1, null, msgs);
      msgs = basicSetRight_1(newRight_1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT_1, newRight_1, newRight_1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataExpr getRight_2()
  {
    return right_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRight_2(DataExpr newRight_2, NotificationChain msgs)
  {
    DataExpr oldRight_2 = right_2;
    right_2 = newRight_2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT_2, oldRight_2, newRight_2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRight_2(DataExpr newRight_2)
  {
    if (newRight_2 != right_2)
    {
      NotificationChain msgs = null;
      if (right_2 != null)
        msgs = ((InternalEObject)right_2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT_2, null, msgs);
      if (newRight_2 != null)
        msgs = ((InternalEObject)newRight_2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT_2, null, msgs);
      msgs = basicSetRight_2(newRight_2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT_2, newRight_2, newRight_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataExprList getRight()
  {
    return right;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRight(DataExprList newRight, NotificationChain msgs)
  {
    DataExprList oldRight = right;
    right = newRight;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT, oldRight, newRight);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRight(DataExprList newRight)
  {
    if (newRight != right)
    {
      NotificationChain msgs = null;
      if (right != null)
        msgs = ((InternalEObject)right).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT, null, msgs);
      if (newRight != null)
        msgs = ((InternalEObject)newRight).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MclrDslPackage.DATA_EXPR__RIGHT, null, msgs);
      msgs = basicSetRight(newRight, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MclrDslPackage.DATA_EXPR__RIGHT, newRight, newRight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MclrDslPackage.DATA_EXPR__LEFT:
        return basicSetLeft(null, msgs);
      case MclrDslPackage.DATA_EXPR__RIGHT_1:
        return basicSetRight_1(null, msgs);
      case MclrDslPackage.DATA_EXPR__RIGHT_2:
        return basicSetRight_2(null, msgs);
      case MclrDslPackage.DATA_EXPR__RIGHT:
        return basicSetRight(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MclrDslPackage.DATA_EXPR__LEFT:
        return getLeft();
      case MclrDslPackage.DATA_EXPR__RIGHT_1:
        return getRight_1();
      case MclrDslPackage.DATA_EXPR__RIGHT_2:
        return getRight_2();
      case MclrDslPackage.DATA_EXPR__RIGHT:
        return getRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MclrDslPackage.DATA_EXPR__LEFT:
        setLeft((DataExpr1)newValue);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT_1:
        setRight_1((DataExpr)newValue);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT_2:
        setRight_2((DataExpr)newValue);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT:
        setRight((DataExprList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.DATA_EXPR__LEFT:
        setLeft((DataExpr1)null);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT_1:
        setRight_1((DataExpr)null);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT_2:
        setRight_2((DataExpr)null);
        return;
      case MclrDslPackage.DATA_EXPR__RIGHT:
        setRight((DataExprList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MclrDslPackage.DATA_EXPR__LEFT:
        return left != null;
      case MclrDslPackage.DATA_EXPR__RIGHT_1:
        return right_1 != null;
      case MclrDslPackage.DATA_EXPR__RIGHT_2:
        return right_2 != null;
      case MclrDslPackage.DATA_EXPR__RIGHT:
        return right != null;
    }
    return super.eIsSet(featureID);
  }

} //DataExprImpl
