/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Act Id Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ActIdSet#getIds <em>Ids</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getActIdSet()
 * @model
 * @generated
 */
public interface ActIdSet extends EObject
{
  /**
   * Returns the value of the '<em><b>Ids</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ids</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ids</em>' containment reference.
   * @see #setIds(ActionNameList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getActIdSet_Ids()
   * @model containment="true"
   * @generated
   */
  ActionNameList getIds();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ActIdSet#getIds <em>Ids</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ids</em>' containment reference.
   * @see #getIds()
   * @generated
   */
  void setIds(ActionNameList value);

} // ActIdSet
