/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constr Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getId <em>Id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getProj <em>Proj</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getRight_id <em>Right id</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getConstrDecl()
 * @model
 * @generated
 */
public interface ConstrDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(ConstrName)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getConstrDecl_Id()
   * @model containment="true"
   * @generated
   */
  ConstrName getId();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(ConstrName value);

  /**
   * Returns the value of the '<em><b>Proj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proj</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proj</em>' containment reference.
   * @see #setProj(ProjDeclList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getConstrDecl_Proj()
   * @model containment="true"
   * @generated
   */
  ProjDeclList getProj();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getProj <em>Proj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proj</em>' containment reference.
   * @see #getProj()
   * @generated
   */
  void setProj(ProjDeclList value);

  /**
   * Returns the value of the '<em><b>Right id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right id</em>' attribute.
   * @see #setRight_id(String)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getConstrDecl_Right_id()
   * @model
   * @generated
   */
  String getRight_id();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ConstrDecl#getRight_id <em>Right id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right id</em>' attribute.
   * @see #getRight_id()
   * @generated
   */
  void setRight_id(String value);

} // ConstrDecl
