/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Expr Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_id <em>Var id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getNum <em>Num</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_true <em>Is true</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_false <em>Is false</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_sqaure_bracket <em>Is sqaure bracket</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_list <em>Data list</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_curly_bracket <em>Is curly bracket</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_colon <em>Is colon</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getBag <em>Bag</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_exp_list <em>Data exp list</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_decl <em>Var decl</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_exp <em>Data exp</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_round_bracket <em>Is round bracket</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_forall <em>Is forall</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_exist <em>Is exist</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_lambda <em>Is lambda</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_list <em>Var list</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm()
 * @model
 * @generated
 */
public interface DataExprTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Var id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var id</em>' reference.
   * @see #setVar_id(VarName)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Var_id()
   * @model
   * @generated
   */
  VarName getVar_id();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_id <em>Var id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var id</em>' reference.
   * @see #getVar_id()
   * @generated
   */
  void setVar_id(VarName value);

  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(int)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Num()
   * @model
   * @generated
   */
  int getNum();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(int value);

  /**
   * Returns the value of the '<em><b>Is true</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is true</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is true</em>' attribute.
   * @see #setIs_true(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_true()
   * @model
   * @generated
   */
  boolean isIs_true();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_true <em>Is true</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is true</em>' attribute.
   * @see #isIs_true()
   * @generated
   */
  void setIs_true(boolean value);

  /**
   * Returns the value of the '<em><b>Is false</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is false</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is false</em>' attribute.
   * @see #setIs_false(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_false()
   * @model
   * @generated
   */
  boolean isIs_false();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_false <em>Is false</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is false</em>' attribute.
   * @see #isIs_false()
   * @generated
   */
  void setIs_false(boolean value);

  /**
   * Returns the value of the '<em><b>Is sqaure bracket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is sqaure bracket</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is sqaure bracket</em>' attribute.
   * @see #setIs_sqaure_bracket(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_sqaure_bracket()
   * @model
   * @generated
   */
  boolean isIs_sqaure_bracket();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_sqaure_bracket <em>Is sqaure bracket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is sqaure bracket</em>' attribute.
   * @see #isIs_sqaure_bracket()
   * @generated
   */
  void setIs_sqaure_bracket(boolean value);

  /**
   * Returns the value of the '<em><b>Data list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data list</em>' containment reference.
   * @see #setData_list(DataExprList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Data_list()
   * @model containment="true"
   * @generated
   */
  DataExprList getData_list();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_list <em>Data list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data list</em>' containment reference.
   * @see #getData_list()
   * @generated
   */
  void setData_list(DataExprList value);

  /**
   * Returns the value of the '<em><b>Is curly bracket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is curly bracket</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is curly bracket</em>' attribute.
   * @see #setIs_curly_bracket(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_curly_bracket()
   * @model
   * @generated
   */
  boolean isIs_curly_bracket();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_curly_bracket <em>Is curly bracket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is curly bracket</em>' attribute.
   * @see #isIs_curly_bracket()
   * @generated
   */
  void setIs_curly_bracket(boolean value);

  /**
   * Returns the value of the '<em><b>Is colon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is colon</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is colon</em>' attribute.
   * @see #setIs_colon(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_colon()
   * @model
   * @generated
   */
  boolean isIs_colon();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_colon <em>Is colon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is colon</em>' attribute.
   * @see #isIs_colon()
   * @generated
   */
  void setIs_colon(boolean value);

  /**
   * Returns the value of the '<em><b>Bag</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bag</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bag</em>' containment reference.
   * @see #setBag(BagEnumEltList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Bag()
   * @model containment="true"
   * @generated
   */
  BagEnumEltList getBag();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getBag <em>Bag</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bag</em>' containment reference.
   * @see #getBag()
   * @generated
   */
  void setBag(BagEnumEltList value);

  /**
   * Returns the value of the '<em><b>Data exp list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data exp list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data exp list</em>' containment reference.
   * @see #setData_exp_list(DataExprList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Data_exp_list()
   * @model containment="true"
   * @generated
   */
  DataExprList getData_exp_list();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_exp_list <em>Data exp list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data exp list</em>' containment reference.
   * @see #getData_exp_list()
   * @generated
   */
  void setData_exp_list(DataExprList value);

  /**
   * Returns the value of the '<em><b>Var decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var decl</em>' containment reference.
   * @see #setVar_decl(VarsDecl)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Var_decl()
   * @model containment="true"
   * @generated
   */
  VarsDecl getVar_decl();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_decl <em>Var decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var decl</em>' containment reference.
   * @see #getVar_decl()
   * @generated
   */
  void setVar_decl(VarsDecl value);

  /**
   * Returns the value of the '<em><b>Data exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data exp</em>' containment reference.
   * @see #setData_exp(DataExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Data_exp()
   * @model containment="true"
   * @generated
   */
  DataExpr getData_exp();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getData_exp <em>Data exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data exp</em>' containment reference.
   * @see #getData_exp()
   * @generated
   */
  void setData_exp(DataExpr value);

  /**
   * Returns the value of the '<em><b>Is round bracket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is round bracket</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is round bracket</em>' attribute.
   * @see #setIs_round_bracket(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_round_bracket()
   * @model
   * @generated
   */
  boolean isIs_round_bracket();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_round_bracket <em>Is round bracket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is round bracket</em>' attribute.
   * @see #isIs_round_bracket()
   * @generated
   */
  void setIs_round_bracket(boolean value);

  /**
   * Returns the value of the '<em><b>Is forall</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is forall</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is forall</em>' attribute.
   * @see #setIs_forall(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_forall()
   * @model
   * @generated
   */
  boolean isIs_forall();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_forall <em>Is forall</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is forall</em>' attribute.
   * @see #isIs_forall()
   * @generated
   */
  void setIs_forall(boolean value);

  /**
   * Returns the value of the '<em><b>Is exist</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is exist</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is exist</em>' attribute.
   * @see #setIs_exist(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_exist()
   * @model
   * @generated
   */
  boolean isIs_exist();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_exist <em>Is exist</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is exist</em>' attribute.
   * @see #isIs_exist()
   * @generated
   */
  void setIs_exist(boolean value);

  /**
   * Returns the value of the '<em><b>Is lambda</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is lambda</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is lambda</em>' attribute.
   * @see #setIs_lambda(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Is_lambda()
   * @model
   * @generated
   */
  boolean isIs_lambda();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#isIs_lambda <em>Is lambda</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is lambda</em>' attribute.
   * @see #isIs_lambda()
   * @generated
   */
  void setIs_lambda(boolean value);

  /**
   * Returns the value of the '<em><b>Var list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var list</em>' containment reference.
   * @see #setVar_list(VarsDeclList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getDataExprTerm_Var_list()
   * @model containment="true"
   * @generated
   */
  VarsDeclList getVar_list();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.DataExprTerm#getVar_list <em>Var list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var list</em>' containment reference.
   * @see #getVar_list()
   * @generated
   */
  void setVar_list(VarsDeclList value);

} // DataExprTerm
