/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eqn Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getCond <em>Cond</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getLeft <em>Left</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getEqnDecl()
 * @model
 * @generated
 */
public interface EqnDecl extends EObject
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(DataExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getEqnDecl_Cond()
   * @model containment="true"
   * @generated
   */
  DataExpr getCond();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(DataExpr value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(DataExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getEqnDecl_Left()
   * @model containment="true"
   * @generated
   */
  DataExpr getLeft();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(DataExpr value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(DataExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getEqnDecl_Right()
   * @model containment="true"
   * @generated
   */
  DataExpr getRight();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.EqnDecl#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(DataExpr value);

} // EqnDecl
