/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.Model#getLeft <em>Left</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.Model#getInit <em>Init</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.Model#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference list.
   * The list contents are of type {@link tuks.mcrl2.dsl.mclrDsl.mCRL2SpecElt}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference list.
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getModel_Left()
   * @model containment="true"
   * @generated
   */
  EList<mCRL2SpecElt> getLeft();

  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference.
   * @see #setInit(Init)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getModel_Init()
   * @model containment="true"
   * @generated
   */
  Init getInit();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.Model#getInit <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' containment reference.
   * @see #getInit()
   * @generated
   */
  void setInit(Init value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link tuks.mcrl2.dsl.mclrDsl.mCRL2SpecElt}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getModel_Right()
   * @model containment="true"
   * @generated
   */
  EList<mCRL2SpecElt> getRight();

} // Model
