/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proc Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getLeft <em>Left</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_plus <em>Is plus</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_par <em>Is par</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_par_right <em>Is par right</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_left_shist <em>Is left shist</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_point <em>Is point</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_or <em>Is or</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getRight <em>Right</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_at <em>Is at</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getUnit_right <em>Unit right</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr()
 * @model
 * @generated
 */
public interface ProcExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ProcExprTerm)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Left()
   * @model containment="true"
   * @generated
   */
  ProcExprTerm getLeft();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ProcExprTerm value);

  /**
   * Returns the value of the '<em><b>Is plus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is plus</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is plus</em>' attribute.
   * @see #setIs_plus(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_plus()
   * @model
   * @generated
   */
  boolean isIs_plus();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_plus <em>Is plus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is plus</em>' attribute.
   * @see #isIs_plus()
   * @generated
   */
  void setIs_plus(boolean value);

  /**
   * Returns the value of the '<em><b>Is par</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is par</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is par</em>' attribute.
   * @see #setIs_par(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_par()
   * @model
   * @generated
   */
  boolean isIs_par();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_par <em>Is par</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is par</em>' attribute.
   * @see #isIs_par()
   * @generated
   */
  void setIs_par(boolean value);

  /**
   * Returns the value of the '<em><b>Is par right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is par right</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is par right</em>' attribute.
   * @see #setIs_par_right(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_par_right()
   * @model
   * @generated
   */
  boolean isIs_par_right();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_par_right <em>Is par right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is par right</em>' attribute.
   * @see #isIs_par_right()
   * @generated
   */
  void setIs_par_right(boolean value);

  /**
   * Returns the value of the '<em><b>Is left shist</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is left shist</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is left shist</em>' attribute.
   * @see #setIs_left_shist(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_left_shist()
   * @model
   * @generated
   */
  boolean isIs_left_shist();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_left_shist <em>Is left shist</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is left shist</em>' attribute.
   * @see #isIs_left_shist()
   * @generated
   */
  void setIs_left_shist(boolean value);

  /**
   * Returns the value of the '<em><b>Is point</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is point</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is point</em>' attribute.
   * @see #setIs_point(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_point()
   * @model
   * @generated
   */
  boolean isIs_point();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_point <em>Is point</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is point</em>' attribute.
   * @see #isIs_point()
   * @generated
   */
  void setIs_point(boolean value);

  /**
   * Returns the value of the '<em><b>Is or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is or</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is or</em>' attribute.
   * @see #setIs_or(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_or()
   * @model
   * @generated
   */
  boolean isIs_or();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_or <em>Is or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is or</em>' attribute.
   * @see #isIs_or()
   * @generated
   */
  void setIs_or(boolean value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ProcExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Right()
   * @model containment="true"
   * @generated
   */
  ProcExpr getRight();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ProcExpr value);

  /**
   * Returns the value of the '<em><b>Is at</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is at</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is at</em>' attribute.
   * @see #setIs_at(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Is_at()
   * @model
   * @generated
   */
  boolean isIs_at();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#isIs_at <em>Is at</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is at</em>' attribute.
   * @see #isIs_at()
   * @generated
   */
  void setIs_at(boolean value);

  /**
   * Returns the value of the '<em><b>Unit right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unit right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit right</em>' containment reference.
   * @see #setUnit_right(DataExprUnit)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExpr_Unit_right()
   * @model containment="true"
   * @generated
   */
  DataExprUnit getUnit_right();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExpr#getUnit_right <em>Unit right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit right</em>' containment reference.
   * @see #getUnit_right()
   * @generated
   */
  void setUnit_right(DataExprUnit value);

} // ProcExpr
