/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proc Expr Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAction <em>Action</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getProc_id <em>Proc id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAss <em>Ass</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getMap_id <em>Map id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_delta <em>Is delta</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_tau <em>Is tau</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_block <em>Is block</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAct_set <em>Act set</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getProc_exp <em>Proc exp</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_allow <em>Is allow</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getMulti_set <em>Multi set</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_hide <em>Is hide</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_grp <em>Is grp</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_sum <em>Is sum</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm()
 * @model
 * @generated
 */
public interface ProcExprTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(Action)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Action()
   * @model containment="true"
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

  /**
   * Returns the value of the '<em><b>Proc id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proc id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc id</em>' reference.
   * @see #setProc_id(ProcName)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Proc_id()
   * @model
   * @generated
   */
  ProcName getProc_id();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getProc_id <em>Proc id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc id</em>' reference.
   * @see #getProc_id()
   * @generated
   */
  void setProc_id(ProcName value);

  /**
   * Returns the value of the '<em><b>Ass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ass</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ass</em>' containment reference.
   * @see #setAss(AssignmentList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Ass()
   * @model containment="true"
   * @generated
   */
  AssignmentList getAss();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAss <em>Ass</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ass</em>' containment reference.
   * @see #getAss()
   * @generated
   */
  void setAss(AssignmentList value);

  /**
   * Returns the value of the '<em><b>Map id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map id</em>' reference.
   * @see #setMap_id(SortName)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Map_id()
   * @model
   * @generated
   */
  SortName getMap_id();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getMap_id <em>Map id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map id</em>' reference.
   * @see #getMap_id()
   * @generated
   */
  void setMap_id(SortName value);

  /**
   * Returns the value of the '<em><b>Is delta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is delta</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is delta</em>' attribute.
   * @see #setIs_delta(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_delta()
   * @model
   * @generated
   */
  boolean isIs_delta();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_delta <em>Is delta</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is delta</em>' attribute.
   * @see #isIs_delta()
   * @generated
   */
  void setIs_delta(boolean value);

  /**
   * Returns the value of the '<em><b>Is tau</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is tau</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is tau</em>' attribute.
   * @see #setIs_tau(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_tau()
   * @model
   * @generated
   */
  boolean isIs_tau();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_tau <em>Is tau</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is tau</em>' attribute.
   * @see #isIs_tau()
   * @generated
   */
  void setIs_tau(boolean value);

  /**
   * Returns the value of the '<em><b>Is block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is block</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is block</em>' attribute.
   * @see #setIs_block(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_block()
   * @model
   * @generated
   */
  boolean isIs_block();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_block <em>Is block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is block</em>' attribute.
   * @see #isIs_block()
   * @generated
   */
  void setIs_block(boolean value);

  /**
   * Returns the value of the '<em><b>Act set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Act set</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Act set</em>' containment reference.
   * @see #setAct_set(ActIdSet)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Act_set()
   * @model containment="true"
   * @generated
   */
  ActIdSet getAct_set();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getAct_set <em>Act set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Act set</em>' containment reference.
   * @see #getAct_set()
   * @generated
   */
  void setAct_set(ActIdSet value);

  /**
   * Returns the value of the '<em><b>Proc exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proc exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proc exp</em>' containment reference.
   * @see #setProc_exp(ProcExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Proc_exp()
   * @model containment="true"
   * @generated
   */
  ProcExpr getProc_exp();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getProc_exp <em>Proc exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Proc exp</em>' containment reference.
   * @see #getProc_exp()
   * @generated
   */
  void setProc_exp(ProcExpr value);

  /**
   * Returns the value of the '<em><b>Is allow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is allow</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is allow</em>' attribute.
   * @see #setIs_allow(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_allow()
   * @model
   * @generated
   */
  boolean isIs_allow();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_allow <em>Is allow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is allow</em>' attribute.
   * @see #isIs_allow()
   * @generated
   */
  void setIs_allow(boolean value);

  /**
   * Returns the value of the '<em><b>Multi set</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multi set</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multi set</em>' containment reference.
   * @see #setMulti_set(MultActIdSet)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Multi_set()
   * @model containment="true"
   * @generated
   */
  MultActIdSet getMulti_set();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getMulti_set <em>Multi set</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multi set</em>' containment reference.
   * @see #getMulti_set()
   * @generated
   */
  void setMulti_set(MultActIdSet value);

  /**
   * Returns the value of the '<em><b>Is hide</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is hide</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is hide</em>' attribute.
   * @see #setIs_hide(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_hide()
   * @model
   * @generated
   */
  boolean isIs_hide();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_hide <em>Is hide</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is hide</em>' attribute.
   * @see #isIs_hide()
   * @generated
   */
  void setIs_hide(boolean value);

  /**
   * Returns the value of the '<em><b>Is grp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is grp</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is grp</em>' attribute.
   * @see #setIs_grp(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_grp()
   * @model
   * @generated
   */
  boolean isIs_grp();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_grp <em>Is grp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is grp</em>' attribute.
   * @see #isIs_grp()
   * @generated
   */
  void setIs_grp(boolean value);

  /**
   * Returns the value of the '<em><b>Is sum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is sum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is sum</em>' attribute.
   * @see #setIs_sum(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Is_sum()
   * @model
   * @generated
   */
  boolean isIs_sum();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#isIs_sum <em>Is sum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is sum</em>' attribute.
   * @see #isIs_sum()
   * @generated
   */
  void setIs_sum(boolean value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference.
   * @see #setVariables(VarsDeclList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProcExprTerm_Variables()
   * @model containment="true"
   * @generated
   */
  VarsDeclList getVariables();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.ProcExprTerm#getVariables <em>Variables</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variables</em>' containment reference.
   * @see #getVariables()
   * @generated
   */
  void setVariables(VarsDeclList value);

} // ProcExprTerm
