/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proj Decl List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProjDeclList#getProj <em>Proj</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.ProjDeclList#getProf <em>Prof</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProjDeclList()
 * @model
 * @generated
 */
public interface ProjDeclList extends EObject
{
  /**
   * Returns the value of the '<em><b>Proj</b></em>' containment reference list.
   * The list contents are of type {@link tuks.mcrl2.dsl.mclrDsl.ProjDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Proj</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Proj</em>' containment reference list.
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProjDeclList_Proj()
   * @model containment="true"
   * @generated
   */
  EList<ProjDecl> getProj();

  /**
   * Returns the value of the '<em><b>Prof</b></em>' containment reference list.
   * The list contents are of type {@link tuks.mcrl2.dsl.mclrDsl.ProjDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prof</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prof</em>' containment reference list.
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getProjDeclList_Prof()
   * @model containment="true"
   * @generated
   */
  EList<ProjDecl> getProf();

} // ProjDeclList
