/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sort Expr Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_bool <em>Is bool</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_pos <em>Is pos</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_nat <em>Is nat</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_int <em>Is int</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_real <em>Is real</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_list <em>Is list</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isSet <em>Set</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isBag <em>Bag</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isFset <em>Fset</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isFbag <em>Fbag</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getExp <em>Exp</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getId <em>Id</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getConst <em>Const</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm()
 * @model
 * @generated
 */
public interface SortExprTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Is bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is bool</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is bool</em>' attribute.
   * @see #setIs_bool(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_bool()
   * @model
   * @generated
   */
  boolean isIs_bool();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_bool <em>Is bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is bool</em>' attribute.
   * @see #isIs_bool()
   * @generated
   */
  void setIs_bool(boolean value);

  /**
   * Returns the value of the '<em><b>Is pos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is pos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is pos</em>' attribute.
   * @see #setIs_pos(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_pos()
   * @model
   * @generated
   */
  boolean isIs_pos();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_pos <em>Is pos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is pos</em>' attribute.
   * @see #isIs_pos()
   * @generated
   */
  void setIs_pos(boolean value);

  /**
   * Returns the value of the '<em><b>Is nat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is nat</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is nat</em>' attribute.
   * @see #setIs_nat(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_nat()
   * @model
   * @generated
   */
  boolean isIs_nat();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_nat <em>Is nat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is nat</em>' attribute.
   * @see #isIs_nat()
   * @generated
   */
  void setIs_nat(boolean value);

  /**
   * Returns the value of the '<em><b>Is int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is int</em>' attribute.
   * @see #setIs_int(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_int()
   * @model
   * @generated
   */
  boolean isIs_int();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_int <em>Is int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is int</em>' attribute.
   * @see #isIs_int()
   * @generated
   */
  void setIs_int(boolean value);

  /**
   * Returns the value of the '<em><b>Is real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is real</em>' attribute.
   * @see #setIs_real(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_real()
   * @model
   * @generated
   */
  boolean isIs_real();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_real <em>Is real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is real</em>' attribute.
   * @see #isIs_real()
   * @generated
   */
  void setIs_real(boolean value);

  /**
   * Returns the value of the '<em><b>Is list</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is list</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is list</em>' attribute.
   * @see #setIs_list(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Is_list()
   * @model
   * @generated
   */
  boolean isIs_list();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isIs_list <em>Is list</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is list</em>' attribute.
   * @see #isIs_list()
   * @generated
   */
  void setIs_list(boolean value);

  /**
   * Returns the value of the '<em><b>Set</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Set</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Set</em>' attribute.
   * @see #setSet(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Set()
   * @model
   * @generated
   */
  boolean isSet();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isSet <em>Set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Set</em>' attribute.
   * @see #isSet()
   * @generated
   */
  void setSet(boolean value);

  /**
   * Returns the value of the '<em><b>Bag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bag</em>' attribute.
   * @see #setBag(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Bag()
   * @model
   * @generated
   */
  boolean isBag();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isBag <em>Bag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bag</em>' attribute.
   * @see #isBag()
   * @generated
   */
  void setBag(boolean value);

  /**
   * Returns the value of the '<em><b>Fset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fset</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fset</em>' attribute.
   * @see #setFset(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Fset()
   * @model
   * @generated
   */
  boolean isFset();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isFset <em>Fset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fset</em>' attribute.
   * @see #isFset()
   * @generated
   */
  void setFset(boolean value);

  /**
   * Returns the value of the '<em><b>Fbag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fbag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fbag</em>' attribute.
   * @see #setFbag(boolean)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Fbag()
   * @model
   * @generated
   */
  boolean isFbag();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#isFbag <em>Fbag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fbag</em>' attribute.
   * @see #isFbag()
   * @generated
   */
  void setFbag(boolean value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(SortExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Exp()
   * @model containment="true"
   * @generated
   */
  SortExpr getExp();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(SortExpr value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(SortName)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Id()
   * @model
   * @generated
   */
  SortName getId();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(SortName value);

  /**
   * Returns the value of the '<em><b>Const</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Const</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const</em>' containment reference.
   * @see #setConst(ConstrDeclList)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getSortExprTerm_Const()
   * @model containment="true"
   * @generated
   */
  ConstrDeclList getConst();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.SortExprTerm#getConst <em>Const</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const</em>' containment reference.
   * @see #getConst()
   * @generated
   */
  void setConst(ConstrDeclList value);

} // SortExprTerm
