/**
 * generated by Xtext 2.11.0.beta2
 */
package tuks.mcrl2.dsl.mclrDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vars Decl List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.VarsDeclList#getData <em>Data</em>}</li>
 *   <li>{@link tuks.mcrl2.dsl.mclrDsl.VarsDeclList#getVarialbes <em>Varialbes</em>}</li>
 * </ul>
 *
 * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getVarsDeclList()
 * @model
 * @generated
 */
public interface VarsDeclList extends ProcExprTerm
{
  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(DataExpr)
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getVarsDeclList_Data()
   * @model containment="true"
   * @generated
   */
  DataExpr getData();

  /**
   * Sets the value of the '{@link tuks.mcrl2.dsl.mclrDsl.VarsDeclList#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(DataExpr value);

  /**
   * Returns the value of the '<em><b>Varialbes</b></em>' containment reference list.
   * The list contents are of type {@link tuks.mcrl2.dsl.mclrDsl.VarsDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Varialbes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varialbes</em>' containment reference list.
   * @see tuks.mcrl2.dsl.mclrDsl.MclrDslPackage#getVarsDeclList_Varialbes()
   * @model containment="true"
   * @generated
   */
  EList<VarsDecl> getVarialbes();

} // VarsDeclList
